'on':
  github:
    branches:
      only: main
jobs:
  cloneRepo:
    uses: git-checkout@v1
    with:
      ref: context.event.github.ref
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C3
  generateText:
    uses: script@v1
    with:
      image: paperspace/transformers-gpu:0.4.0
      script: |-
        cp -R /inputs/repo /nlp
        cd /nlp
        pip3 install -U transformers
        python3 nlp_text_generation.py
        mv output.txt /outputs/generatedText
        ls "-aFlR" /outputs/generatedText
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      generatedText:
        type: dataset
        with:
          ref: demo-dataset
    resources:
      instance-type: C5
    name: test
    run: free -m
